# NumPy 广播

Refrences:     
https://www.tutorialspoint.com/numpy/index.htm      
https://www.jianshu.com/p/57e3c0a92f3a

术语广播是指 NumPy 在算术运算期间处理不同形状的数组的能力。 对数组的算术运算通常在相应的元素上进行。 如果两个阵列具有完全相同的形状，则这些操作被无缝执行。

In [2]:
import numpy as np

In [3]:
# sample 1
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print a * b

[ 10  40  90 160]


如果数组的维数不相同，则元素到元素的操作是不可能的。然而NumPy中任然可以对形状不相似的数组进行操作，因为他们具有广播功能。
较小的数组会被广播到较大的数组，以便使他们的形状可兼容。

如果满足以下规则，可以进行广播（略抽象...）：     
* `ndim`较小的数组会在前面追加一个长度为1的维度（现在还不太理解。。）
* 输出数组的每个维度的大小是输入数组该维度大小的最大值
* 如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则在计算中可它。
* 如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。

如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。

* 数组拥有相同形状。
* 数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。
* 数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。

In [8]:
# sample 2
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print a + b

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


下面图片展示了数组b如何通过广播与数组a兼容：     
![](imgs/numpy-array-broadcast.jpg)

# NumPy 数组上的迭代
NpmPy包含一个数组迭代器对象numpy.nditer。他是一个有效的多维迭代器对象，可以用于在数组上进行迭代。数组的每个元素可以使用python的标准`Iterator`接口来访问。

In [13]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print 'origin array is: \n %s' % a
print "-------遍历数组-------"
for x in np.nditer(a):
    print x,

origin array is: 
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
-------遍历数组-------
0 5 10 15 20 25 30 35 40 45 50 55
